-- SQLite
SELECT E.ID AS 'CÓDIGO',
       E.NAME AS 'NOME',
       E.[PHONE NUMBER] AS 'NUMERO DE TELEFONE',
       E.CONTRACT_DATE AS 'DATA DO CONTRATO',
       P.DESCRIPTION AS 'CARGO'
FROM EMPLOYEES AS E
INNER JOIN POSITIONS AS P ON (E.POSITION_ID = P.ID);