-- SQLite
SELECT C.ID AS 'CÓDIGO',
       C.NAME AS 'NOME',
       C.LASTNAME AS 'SOBRENOME',
       C.PHONE AS 'TELEFONE',
       C.EMAIL,
       C.ADDRESS AS 'ENDERECO',
       C.CITY AS 'CIDADE',
       C.STATE AS 'ESTADO',
       C.BIRTH_DATE AS 'DATA DE NASCIMENTO',
       COUNT(L.ID) AS 'QUANTIDADE DE LOCACAO'
FROM CUSTOMERS AS C
LEFT JOIN LOCATIONS AS L ON (C.ID = L.CUSTOMER_ID)
GROUP BY C.NAME
HAVING COUNT(L.ID) >= 2;